import { useState, type FormEvent } from 'react'
import { addGoalContribution, deleteBill, deleteGoal, deleteSubscription, markBillPaid, saveBill, saveGoal, saveSubscription } from '../db/actions'
import type { Account, Bill, Category, Frequency, Goal, Subscription } from '../db/types'
import { formatCurrency } from '../lib/currency'
import { todayInputValue } from '../lib/date'
import { BottomSheet } from './BottomSheet'

export function GoalsManager({ goals, currency }: { goals: Goal[]; currency: string }) {
  const [editing, setEditing] = useState<Goal>(); const [open, setOpen] = useState(false); const [contributing, setContributing] = useState<Goal>(); const [amount, setAmount] = useState(''); const [error, setError] = useState('')
  const openGoal = (goal?: Goal) => { setEditing(goal ? { ...goal } : { name: '', targetAmount: 0, savedAmount: 0 }); setError(''); setOpen(true) }
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!editing) return; try { await saveGoal(editing); setOpen(false) } catch (e) { setError(e instanceof Error ? e.message : 'Could not save goal.') } }
  const contribute = async (event: FormEvent) => { event.preventDefault(); if (!contributing?.id) return; try { await addGoalContribution(contributing.id, Number(amount)); setContributing(undefined) } catch (e) { setError(e instanceof Error ? e.message : 'Could not add contribution.') } }
  return <section><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Savings goals</h2><p className="mt-1 text-sm text-slate-500">Track the money you are setting aside.</p></div><button className="min-h-11 rounded-2xl bg-blue-600 px-4 font-bold text-white" onClick={() => openGoal()}>Add goal</button></div><div className="mt-4 space-y-3">{goals.length ? goals.map(goal => { const pct = Math.min(100, goal.savedAmount / goal.targetAmount * 100); return <article key={goal.id} className="rounded-[1.5rem] bg-white p-4 shadow-sm ring-1 ring-slate-200/80"><button className="w-full text-left" onClick={() => openGoal(goal)}><div className="flex justify-between gap-3"><span className="font-bold">{goal.name}</span><span className="font-bold text-blue-700">{Math.round(pct)}%</span></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${pct}%`}} /></div><p className="mt-2 text-sm font-semibold text-slate-500">{formatCurrency(goal.savedAmount,currency)} of {formatCurrency(goal.targetAmount,currency)}{goal.targetDate ? ` · target ${goal.targetDate}` : ''}</p></button><div className="mt-3 flex gap-2 border-t border-slate-100 pt-3"><button className="min-h-11 flex-1 rounded-xl bg-blue-50 font-bold text-blue-700" onClick={() => { setContributing(goal); setAmount(''); setError('') }}>Add savings</button><button className="min-h-11 px-3 font-bold text-rose-600" onClick={() => goal.id && void deleteGoal(goal.id)}>Delete</button></div></article> }) : <button className="mt-2 min-h-28 w-full rounded-[1.5rem] border-2 border-dashed border-slate-200 bg-white text-sm font-semibold text-slate-500" onClick={() => openGoal()}>No savings goals yet. Add one to get started.</button>}</div>
  <BottomSheet open={open} title={editing?.id ? 'Edit goal' : 'Add goal'} onClose={() => setOpen(false)}>{editing && <form className="space-y-4 py-4" onSubmit={e=>void submit(e)}><Input label="Goal name" value={editing.name} onChange={v=>setEditing({...editing,name:v})}/><NumberInput label="Target amount" value={editing.targetAmount} onChange={v=>setEditing({...editing,targetAmount:v})}/><NumberInput label="Already saved" value={editing.savedAmount} onChange={v=>setEditing({...editing,savedAmount:v})}/><DateInput label="Target date (optional)" value={editing.targetDate ?? ''} onChange={v=>setEditing({...editing,targetDate:v||undefined})}/><ErrorText value={error}/><SaveButton text="Save goal" /></form>}</BottomSheet>
  <BottomSheet open={Boolean(contributing)} title="Add savings" onClose={()=>setContributing(undefined)}>{contributing && <form className="space-y-4 py-4" onSubmit={e=>void contribute(e)}><NumberInput label={`Contribution to ${contributing.name}`} value={Number(amount)||0} onChange={v=>setAmount(String(v))}/><ErrorText value={error}/><SaveButton text="Add contribution" /></form>}</BottomSheet></section>
}

export function BillsManager({ bills, accounts, categories, currency }: { bills: Bill[]; accounts: Account[]; categories: Category[]; currency: string }) {
  const [editing,setEditing]=useState<Bill>(); const [open,setOpen]=useState(false); const [error,setError]=useState(''); const billsCategory=categories.find(c=>c.name==='Bills'&&c.type==='expense')?.id ?? categories.find(c=>c.type==='expense')?.id
  const openBill=(bill?:Bill)=>{setEditing(bill?{...bill}:{name:'',amount:0,dueDate:todayInputValue(),repeat:'none',paid:false,accountId:accounts[0]?.id,categoryId:billsCategory,note:''});setError('');setOpen(true)}
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!editing)return;try{await saveBill(editing);setOpen(false)}catch(err){setError(err instanceof Error?err.message:'Could not save bill.')}}
  return <section><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Bill reminders</h2><p className="mt-1 text-sm text-slate-500">Mark paid to record an expense.</p></div><button className="min-h-11 rounded-2xl bg-blue-600 px-4 font-bold text-white" onClick={()=>openBill()}>Add bill</button></div><div className="mt-4 space-y-3">{bills.length?bills.map(bill=>{const delta=Math.ceil((new Date(`${bill.dueDate}T00:00:00`).getTime()-new Date(`${todayInputValue()}T00:00:00`).getTime())/86400000);const label=bill.paid?'Paid':delta<0?`${Math.abs(delta)} days overdue`:delta===0?'Due today':`Due in ${delta} days`;return <article key={bill.id} className="rounded-[1.5rem] bg-white p-4 shadow-sm ring-1 ring-slate-200/80"><button className="w-full text-left" onClick={()=>openBill(bill)}><div className="flex justify-between gap-3"><span className="font-bold">{bill.name}</span><span className="font-bold text-rose-600">{formatCurrency(bill.amount,currency)}</span></div><p className={`mt-1 text-sm font-semibold ${bill.paid?'text-emerald-600':delta<0?'text-rose-600':'text-slate-500'}`}>{label} · {bill.dueDate}</p></button><div className="mt-3 flex gap-2 border-t border-slate-100 pt-3">{!bill.paid&&<button className="min-h-11 flex-1 rounded-xl bg-emerald-50 font-bold text-emerald-700" onClick={()=>bill.id&&void markBillPaid(bill.id)}>Mark paid</button>}<button className="min-h-11 px-3 font-bold text-rose-600" onClick={()=>bill.id&&void deleteBill(bill.id)}>Delete</button></div></article>}) : <button className="mt-2 min-h-28 w-full rounded-[1.5rem] border-2 border-dashed border-slate-200 bg-white text-sm font-semibold text-slate-500" onClick={()=>openBill()}>No bills yet. Add one to get a due-date reminder.</button>}</div>
  <BottomSheet open={open} title={editing?.id?'Edit bill':'Add bill'} onClose={()=>setOpen(false)}>{editing&&<form className="space-y-4 py-4" onSubmit={e=>void submit(e)}><Input label="Bill name" value={editing.name} onChange={v=>setEditing({...editing,name:v})}/><NumberInput label="Amount" value={editing.amount} onChange={v=>setEditing({...editing,amount:v})}/><DateInput label="Due date" value={editing.dueDate} onChange={v=>setEditing({...editing,dueDate:v})}/><Select label="Repeat" value={editing.repeat} onChange={v=>setEditing({...editing,repeat:v as Bill['repeat']})} options={[['none','Does not repeat'],['weekly','Weekly'],['monthly','Monthly'],['yearly','Yearly']]}/><Select label="Payment account" value={String(editing.accountId??'')} onChange={v=>setEditing({...editing,accountId:Number(v)})} options={accounts.map(a=>[String(a.id),a.name])}/><Select label="Expense category" value={String(editing.categoryId??'')} onChange={v=>setEditing({...editing,categoryId:Number(v)})} options={categories.filter(c=>c.type==='expense').map(c=>[String(c.id),`${c.icon} ${c.name}`])}/><Input label="Note (optional)" value={editing.note??''} onChange={v=>setEditing({...editing,note:v})}/><ErrorText value={error}/><SaveButton text="Save bill" /></form>}</BottomSheet></section>
}

const presets=[['Netflix','🎬'],['Spotify','🎵'],['YouTube Premium','▶️'],['iCloud','☁️'],['Google One','G'],['ChatGPT','✦']]
export function SubscriptionsManager({ subscriptions, accounts, categories, currency }: { subscriptions: Subscription[]; accounts: Account[]; categories: Category[]; currency: string }) {
  const [editing,setEditing]=useState<Subscription>();const [open,setOpen]=useState(false);const [error,setError]=useState('');const expense=categories.filter(c=>c.type==='expense');const defaultCat=categories.find(c=>c.name==='Subscriptions')?.id??expense[0]?.id
  const monthly=subscriptions.filter(s=>s.status==='active').reduce((sum,s)=>sum+(s.cycle==='weekly'?s.amount*52/12:s.cycle==='yearly'?s.amount/12:s.amount),0)
  const openSub=(sub?:Subscription,preset?:string[])=>{setEditing(sub?{...sub}:{name:preset?.[0]??'',icon:preset?.[1]??'🔁',amount:0,cycle:'monthly',nextBillingDate:todayInputValue(),categoryId:defaultCat??0,accountId:accounts[0]?.id??0,status:'active',note:'',color:'#2563eb'});setError('');setOpen(true)}
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!editing)return;try{await saveSubscription(editing);setOpen(false)}catch(err){setError(err instanceof Error?err.message:'Could not save subscription.')}}
  return <section><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Subscriptions</h2><p className="mt-1 text-sm text-slate-500">Manage renewals and recurring costs.</p></div><button className="min-h-11 rounded-2xl bg-blue-600 px-4 font-bold text-white" onClick={()=>openSub()}>Add subscription</button></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs font-bold uppercase text-blue-600">Monthly</p><p className="mt-2 font-bold text-blue-800">{formatCurrency(monthly,currency)}</p></div><div className="rounded-2xl bg-slate-100 p-4"><p className="text-xs font-bold uppercase text-slate-500">Yearly</p><p className="mt-2 font-bold">{formatCurrency(monthly*12,currency)}</p></div></div><div className="mt-4"><p className="text-sm font-bold text-slate-600">Quick presets</p><div className="mt-2 flex gap-2 overflow-x-auto pb-1">{presets.map(p=><button key={p[0]} className="min-h-11 shrink-0 rounded-xl bg-slate-100 px-3 text-sm font-bold" onClick={()=>openSub(undefined,p)}>{p[1]} {p[0]}</button>)}</div></div><div className="mt-4 space-y-3">{subscriptions.length?subscriptions.map(s=><article key={s.id} className="rounded-[1.5rem] bg-white p-4 shadow-sm ring-1 ring-slate-200/80"><button className="w-full text-left" onClick={()=>openSub(s)}><div className="flex justify-between gap-3"><span className="font-bold">{s.icon??'🔁'} {s.name}</span><span className="font-bold text-rose-600">{formatCurrency(s.amount,currency)}</span></div><p className="mt-1 text-sm capitalize text-slate-500">{s.status} · {s.cycle} · next {s.nextBillingDate}</p></button><div className="mt-3 flex justify-between border-t border-slate-100 pt-3"><button className="min-h-11 px-3 text-sm font-bold text-blue-700" onClick={()=>openSub(s)}>Edit</button><button className="min-h-11 px-3 text-sm font-bold text-rose-600" onClick={()=>s.id&&void deleteSubscription(s.id)}>Delete</button></div></article>):<p className="rounded-[1.5rem] border-2 border-dashed border-slate-200 p-5 text-center text-sm font-semibold text-slate-500">No subscriptions yet.</p>}</div>
  <BottomSheet open={open} title={editing?.id?'Edit subscription':'Add subscription'} onClose={()=>setOpen(false)}>{editing&&<form className="space-y-4 py-4" onSubmit={e=>void submit(e)}><div className="grid grid-cols-[5rem_1fr] gap-3"><Input label="Icon" value={editing.icon??''} onChange={v=>setEditing({...editing,icon:v})}/><Input label="Name" value={editing.name} onChange={v=>setEditing({...editing,name:v})}/></div><NumberInput label="Amount" value={editing.amount} onChange={v=>setEditing({...editing,amount:v})}/><Select label="Billing cycle" value={editing.cycle} onChange={v=>setEditing({...editing,cycle:v as Frequency})} options={[['weekly','Weekly'],['monthly','Monthly'],['yearly','Yearly']]}/><DateInput label="Next billing date" value={editing.nextBillingDate} onChange={v=>setEditing({...editing,nextBillingDate:v,anchorDay:Number(v.slice(8,10))})}/><Select label="Category" value={String(editing.categoryId)} onChange={v=>setEditing({...editing,categoryId:Number(v)})} options={expense.map(c=>[String(c.id),`${c.icon} ${c.name}`])}/><Select label="Payment account" value={String(editing.accountId)} onChange={v=>setEditing({...editing,accountId:Number(v)})} options={accounts.map(a=>[String(a.id),a.name])}/><Select label="Status" value={editing.status} onChange={v=>setEditing({...editing,status:v as Subscription['status']})} options={[['active','Active'],['paused','Paused'],['cancelled','Cancelled']]}/><Input label="Note (optional)" value={editing.note} onChange={v=>setEditing({...editing,note:v})}/><ErrorText value={error}/><SaveButton text="Save subscription" /></form>}</BottomSheet></section>
}

function Input({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-sm font-bold text-slate-700">{label}<input className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 px-4 text-base" value={value} onChange={e=>onChange(e.target.value)} /></label>}
function NumberInput({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="block text-sm font-bold text-slate-700">{label}<input type="number" min="0" step="0.01" required className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 px-4 text-base" value={value||''} onChange={e=>onChange(Number(e.target.value))}/></label>}
function DateInput({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-sm font-bold text-slate-700">{label}<input type="date" className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 px-4 text-base" value={value} onInput={e=>onChange(e.currentTarget.value)}/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="block text-sm font-bold text-slate-700">{label}<select className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-white px-4 text-base" value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function ErrorText({value}:{value:string}){return value?<p className="rounded-2xl bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{value}</p>:null}
function SaveButton({text}:{text:string}){return <button type="submit" className="min-h-12 w-full rounded-2xl bg-blue-600 px-4 font-bold text-white">{text}</button>}
